### ISSUE TITLE
Decide on SQL variant

### ISSUE THREAD

**Issue by hsercanatli** [entoneorg/entone#11]
Do research on SQL variants.

**Comment by hsercanatli** [comment]
I'll inform you after setting the Django environment @sertansenturk

**Comment by sertansenturk** [comment]
I think postgresql is good for our current needs + we should mirror Dunya, which uses postgresql. 

I have set postgresql in the dev environment and I suggest we stick o that for the time being.

**Comment by hsercanatli** [comment]
I agree with you. We can start with postgresql.
