### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by hsercanatli** [entoneorg/entone#5]

**Comment by sertansenturk** [comment]
aws account created, the next step is to create the machine instance itself.

**Comment by sertansenturk** [comment]
OK, it seems I had to go through a manual check, but now we must (or should be) able to use everything in AWS.

It seems, setting an instance is more complex in AWS.  The most convenient way to set up a server + Django app + PostgreSQL is using Elastic Beanstalk (https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/GettingStarted.html?icmpid=docs_elasticbeanstalk_console), but it will take some time to learn. I'm creating another issue for that

**Comment by sertansenturk** [comment]
http://www.1strategy.com/blog/2017/05/23/tutorial-django-elastic-beanstalk/

**Comment by sertansenturk** [comment]
I have set up a development server here: http://entoneorg-dev.us-west-2.elasticbeanstalk.com/

We should discuss how we proceed with the production and handle this issue accordingly

**Comment by hsercanatli** [comment]
@sertansenturk I think everything seems working from the server side as an initial step. As a reviewer, I can close this issue after getting approval from you.
